# Generated by Django 5.2.14 on 2026-05-17 21:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('session_date', models.DateField(verbose_name='تاريخ الجلسة')),
                ('status', models.CharField(choices=[('open', 'مفتوحة'), ('closed', 'مغلقة')], default='open', max_length=20, verbose_name='حالة الجلسة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
            ],
            options={
                'verbose_name': 'جلسة لجنة',
                'verbose_name_plural': 'جلسات اللجنة',
                'ordering': ['-session_date'],
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('full_name', models.CharField(max_length=255, verbose_name='اسم الطبيب')),
            ],
            options={
                'verbose_name': 'طبيب',
                'verbose_name_plural': 'الأطباء',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('national_id', models.CharField(max_length=14, unique=True, verbose_name='الرقم القومي')),
                ('full_name', models.CharField(max_length=255, verbose_name='اسم المريض')),
                ('birth_date', models.DateField(verbose_name='تاريخ الميلاد')),
                ('gender', models.CharField(choices=[('male', 'ذكر'), ('female', 'أنثى')], max_length=10, verbose_name='النوع')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف')),
                ('governorate', models.CharField(max_length=100, verbose_name='محافظة السكن')),
                ('affiliated_branch', models.CharField(max_length=255, verbose_name='الفرع التابع له')),
                ('diagnosis', models.TextField(verbose_name='التشخيص')),
            ],
            options={
                'verbose_name': 'مريض',
                'verbose_name_plural': 'المرضى',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('category', models.CharField(choices=[('therapeutic', 'إجراء علاجي'), ('radiology', 'فحوصات أشعة'), ('laboratory', 'تحاليل طبية')], max_length=50, verbose_name='التصنيف')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='اسم الإجراء')),
                ('requires_referral', models.BooleanField(default=False, verbose_name='يتطلب تحويل؟')),
            ],
            options={
                'verbose_name': 'إجراء',
                'verbose_name_plural': 'الإجراءات',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ReferralCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الجهة')),
                ('address', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CommitteeCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('status', models.CharField(choices=[('pending', 'في انتظار العرض'), ('reviewed', 'تم العرض')], default='pending', max_length=20, verbose_name='الحالة')),
                ('committee_date', models.DateField(verbose_name='تاريخ اللجنة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('committee_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='committee.committeesession')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_cases', to='committee.patient', verbose_name='المريض')),
            ],
            options={
                'verbose_name': 'عرض لجنة',
                'verbose_name_plural': 'عروض اللجنة',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='committeesession',
            name='doctors',
            field=models.ManyToManyField(related_name='committee_sessions', to='committee.doctor', verbose_name='الأطباء'),
        ),
        migrations.CreateModel(
            name='PatientDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('document_type', models.CharField(choices=[('national_id', 'البطاقة الشخصية'), ('birth_certificate', 'شهادة الميلاد'), ('insurance_card', 'البطاقة الصحية / الكارنيه'), ('other', 'أخرى')], max_length=50, verbose_name='نوع المستند')),
                ('file', models.FileField(upload_to='patient_documents/', verbose_name='الملف')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='committee.patient', verbose_name='المريض')),
            ],
            options={
                'verbose_name': 'مستند مريض',
                'verbose_name_plural': 'مستندات المرضى',
            },
        ),
        migrations.CreateModel(
            name='CommitteeRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('recommendation_text', models.TextField(verbose_name='قرار اللجنة')),
                ('notes', models.TextField(blank=True)),
                ('committee_case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation', to='committee.committeecase')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='committee.procedure')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('referral_number', models.CharField(max_length=50, unique=True, verbose_name='رقم التحويل')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('cancelled', 'ملغي')], default='active', max_length=20, verbose_name='الحالة')),
                ('cancellation_reason', models.TextField(blank=True, verbose_name='سبب الإلغاء')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referrals', to='committee.committeerecommendation', verbose_name='التوصية')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='committee.referralcenter', verbose_name='الجهة المحول إليها')),
            ],
            options={
                'verbose_name': 'تحويل',
                'verbose_name_plural': 'التحويلات',
                'ordering': ['-created_at'],
            },
        ),
    ]
