# Generated by Django 5.2.14 on 2026-05-16 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('national_id', models.CharField(max_length=14, unique=True, verbose_name='الرقم القومي')),
                ('full_name', models.CharField(max_length=255, verbose_name='اسم المريض')),
                ('birth_date', models.DateField(verbose_name='تاريخ الميلاد')),
                ('gender', models.CharField(choices=[('male', 'ذكر'), ('female', 'أنثى')], max_length=10, verbose_name='النوع')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف')),
                ('governorate', models.CharField(max_length=100, verbose_name='محافظة السكن')),
                ('affiliated_branch', models.CharField(max_length=255, verbose_name='الفرع التابع له')),
                ('diagnosis', models.TextField(verbose_name='التشخيص')),
            ],
            options={
                'verbose_name': 'مريض',
                'verbose_name_plural': 'المرضى',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('category', models.CharField(choices=[('therapeutic', 'إجراء علاجي'), ('radiology', 'فحوصات أشعة'), ('laboratory', 'تحاليل طبية')], max_length=50, verbose_name='التصنيف')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='اسم الإجراء')),
            ],
            options={
                'verbose_name': 'إجراء',
                'verbose_name_plural': 'الإجراءات',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CommitteeCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('committee_date', models.DateField(verbose_name='تاريخ اللجنة')),
                ('diagnosis_details', models.TextField(verbose_name='تفاصيل التشخيص')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'مقبول'), ('rejected', 'مرفوض'), ('follow_up', 'متابعة')], default='pending', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='committee.patient', verbose_name='المريض')),
            ],
            options={
                'verbose_name': 'حالة لجنة',
                'verbose_name_plural': 'حالات اللجنة',
                'ordering': ['-committee_date'],
            },
        ),
        migrations.CreateModel(
            name='PatientDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('document_type', models.CharField(choices=[('national_id', 'البطاقة الشخصية'), ('birth_certificate', 'شهادة الميلاد'), ('insurance_card', 'البطاقة الصحية / الكارنيه'), ('other', 'أخرى')], max_length=50, verbose_name='نوع المستند')),
                ('file', models.FileField(upload_to='patient_documents/', verbose_name='الملف')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='committee.patient', verbose_name='المريض')),
            ],
            options={
                'verbose_name': 'مستند مريض',
                'verbose_name_plural': 'مستندات المرضى',
            },
        ),
        migrations.CreateModel(
            name='CommitteeRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('sessions_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='عدد الجلسات')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='committee.committeecase', verbose_name='الحالة')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recommendations', to='committee.procedure', verbose_name='الإجراء')),
            ],
            options={
                'verbose_name': 'توصية لجنة',
                'verbose_name_plural': 'توصيات اللجنة',
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('referral_number', models.CharField(max_length=50, unique=True, verbose_name='رقم التحويل')),
                ('referred_to', models.CharField(max_length=255, verbose_name='الجهة المحول إليها')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('cancelled', 'ملغي')], default='active', max_length=20, verbose_name='الحالة')),
                ('cancellation_reason', models.TextField(blank=True, verbose_name='سبب الإلغاء')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referrals', to='committee.committeerecommendation', verbose_name='التوصية')),
            ],
            options={
                'verbose_name': 'تحويل',
                'verbose_name_plural': 'التحويلات',
                'ordering': ['-created_at'],
            },
        ),
    ]
